spring:
  application:
    name: spring-example-template
  config:
    activate:
      on-profile: local

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

server:
  shutdown: graceful

security:
  jwt:
    secret-base64: ${JWT_SECRET_BASE64}
    issuer: spring-example-template
    audience: spring-example-template-api
    access-token-cookie-name: access-token
    allowed-clock-skew: 30s
