CREATE TABLE user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    role VARCHAR(20) NOT NULL,
    restriction_reason VARCHAR(500),
    restriction_ends_at TIMESTAMPTZ,
    withdrawn_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX uq_user_account_active_email
    ON user_account (email)
    WHERE status <> 'WITHDRAWN';

CREATE INDEX ix_user_account_withdrawn_at
    ON user_account (withdrawn_at)
    WHERE status = 'WITHDRAWN';
